apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    env: production
    security: high
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-staging
  labels:
    env: staging
    security: standard
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
