apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-visibility-oidc
subjects:
- kind: Group
  name: "oidc:ci-deployers"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-ci-deployer
  apiGroup: rbac.authorization.k8s.io
